/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicPluginConnectRouteImport } from './routes/api/public/plugin/connect'
import { Route as ApiPublicPluginPollRouteImport } from './routes/api/public/plugin/poll'
import { Route as ApiPublicPluginResultRouteImport } from './routes/api/public/plugin/result'
import { Route as ApiPublicPluginTreeRouteImport } from './routes/api/public/plugin/tree'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPluginConnectRoute = ApiPublicPluginConnectRouteImport.update({
  id: '/api/public/plugin/connect',
  path: '/api/public/plugin/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPluginPollRoute = ApiPublicPluginPollRouteImport.update({
  id: '/api/public/plugin/poll',
  path: '/api/public/plugin/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPluginResultRoute = ApiPublicPluginResultRouteImport.update({
  id: '/api/public/plugin/result',
  path: '/api/public/plugin/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPluginTreeRoute = ApiPublicPluginTreeRouteImport.update({
  id: '/api/public/plugin/tree',
  path: '/api/public/plugin/tree',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/plugin/connect': typeof ApiPublicPluginConnectRoute
  '/api/public/plugin/poll': typeof ApiPublicPluginPollRoute
  '/api/public/plugin/result': typeof ApiPublicPluginResultRoute
  '/api/public/plugin/tree': typeof ApiPublicPluginTreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/plugin/connect': typeof ApiPublicPluginConnectRoute
  '/api/public/plugin/poll': typeof ApiPublicPluginPollRoute
  '/api/public/plugin/result': typeof ApiPublicPluginResultRoute
  '/api/public/plugin/tree': typeof ApiPublicPluginTreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/plugin/connect': typeof ApiPublicPluginConnectRoute
  '/api/public/plugin/poll': typeof ApiPublicPluginPollRoute
  '/api/public/plugin/result': typeof ApiPublicPluginResultRoute
  '/api/public/plugin/tree': typeof ApiPublicPluginTreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/chat'
    | '/api/public/plugin/connect'
    | '/api/public/plugin/poll'
    | '/api/public/plugin/result'
    | '/api/public/plugin/tree'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/chat'
    | '/api/public/plugin/connect'
    | '/api/public/plugin/poll'
    | '/api/public/plugin/result'
    | '/api/public/plugin/tree'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/api/chat'
    | '/api/public/plugin/connect'
    | '/api/public/plugin/poll'
    | '/api/public/plugin/result'
    | '/api/public/plugin/tree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicPluginConnectRoute: typeof ApiPublicPluginConnectRoute
  ApiPublicPluginPollRoute: typeof ApiPublicPluginPollRoute
  ApiPublicPluginResultRoute: typeof ApiPublicPluginResultRoute
  ApiPublicPluginTreeRoute: typeof ApiPublicPluginTreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/connect': {
      id: '/api/public/plugin/connect'
      path: '/api/public/plugin/connect'
      fullPath: '/api/public/plugin/connect'
      preLoaderRoute: typeof ApiPublicPluginConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/poll': {
      id: '/api/public/plugin/poll'
      path: '/api/public/plugin/poll'
      fullPath: '/api/public/plugin/poll'
      preLoaderRoute: typeof ApiPublicPluginPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/result': {
      id: '/api/public/plugin/result'
      path: '/api/public/plugin/result'
      fullPath: '/api/public/plugin/result'
      preLoaderRoute: typeof ApiPublicPluginResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/tree': {
      id: '/api/public/plugin/tree'
      path: '/api/public/plugin/tree'
      fullPath: '/api/public/plugin/tree'
      preLoaderRoute: typeof ApiPublicPluginTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicPluginConnectRoute: ApiPublicPluginConnectRoute,
  ApiPublicPluginPollRoute: ApiPublicPluginPollRoute,
  ApiPublicPluginResultRoute: ApiPublicPluginResultRoute,
  ApiPublicPluginTreeRoute: ApiPublicPluginTreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
